services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospitaldb
    ports:
      - "3306:3306"

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "80:80"

  app:
    build:
      dockerfile: ./Dockerfile
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/hospitaldb
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:8080"
    working_dir: /code
    entrypoint: [ "mvn", "clean", "quarkus:dev" ]
    volumes:
      - .:/code
